apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi
# Deployment specifications
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  #this part configure a pod within a deployment,with his own metadata and spec
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: kubernetes-devops-project-fastapi:latest  # Remplacez par l'image construite
          ports:
            - containerPort: 5000
        # Should i add Db config here?
