apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: standard
type: Opaque
data:
  # Les valeurs doivent être encodées en base64 (par exemple "password" -> cGFzc3dvcmQ=)
  # Nous pouvons également passer par la maniere impérative et ne pas avoir á coder le mot de passe
  POSTGRES_PASSWORD: cGFzc3dvcmQ=


